env:
  browser: true
  es2021: true
extends: ['htmlacademy/es6', 'plugin:react/recommended']
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins: [
  'react',
  'only-warn'
]
settings:
  react:
    version: '17'
rules: {}
